sudo: required
os:
- linux
dist: trusty
language: go
node_js:
- node
matrix:
  allow_failures: 
cache:
- apt: true
- directories: 
before_install:
- go get ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
install:
- go test ./... -v -covermode=count -coverprofile=coverage.out
- goveralls -coverprofile=coverage.out -service=travis-pro -repotoken $COVERALLS_TOKEN
- CGO_ENABLED=0 go build
before_script: 
script: 
deploy: 
after_success: 
branches: 
addons:
  apt:
    packages: 
env:
  global:
    secure: lztMwrmNchTjFIkmVyLQS383HbMLEja2oP2MfYv/MlFsLcxo1Uo/Lr6yvVM2MVWiZ0dPi3XBR/sTxn+GxNvD+RHPePBuzLQd72HqoaKOnSBoNa8Dl/dpD6EB8aFU52qGRTj2TPhOeOtL7NGyAGZGvT/KI7XXlZi4qOv5gSnNUUnrT8jnpThihbkjezPoOzLrQXGppHv6lzH1HEKnYB23WKku5eRDJzLZ+Y1IKF8jqlrnhZh1a4j2HVhCIwc3rqWeClu1RV9h6nHMBhUGbjVQfyMsG2NMSReBSyg/bKpBx4FBGSUPAuwuK6dU59spEkyoHH1hjsbIGhT83BEiBrSEyqQu9YkpkXFPIOZw5dabOIh4e6fj7k9498meBMD6APIpRCP2KOEQDEwZqQFjg2+i8xLAn2818Ommpk41XgGG0mogIELAmHaD77BZZuAeS4btAZN8wWimgEQyCyple79S8T9qQ5LB/atYgBiS2ZiNJnOrtM7pouXAeDU/psnzmYJ8rFbS076JF7STR8h+j9o+3AOSo/L8fiMstdgq/YiUwhedM4+Obxv5OK2SnKXsC1PmM28yH57hHzjM07qjgBe5qmovLwJD/s1ARvHkQnhFp/DqzmJCpP4DixiPc1k83xBRly75B0j/HUQDujIj8DVTckUqIVIAgfFyyQkGN8S7of0=
