sudo: required
os:
- linux
dist: trusty
language: go
node_js:
- node
matrix:
  allow_failures: 
cache:
- apt: true
- directories: 
before_install:
- go get ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
install:
- go test ./... -v -covermode=count -coverprofile=coverage.out
- goveralls -coverprofile=coverage.out -service=travis-pro -repotoken $COVERALLS_TOKEN
- CGO_ENABLED=0 go build
before_script: 
script: 
deploy: 
after_success: 
branches: 
addons:
  apt:
    packages: 
env:
  global:
  - secure: CzvJ2R8eSzC708LnLiUwgOaXzExoQgdZzHIUbaKnUVDHIwUTGCFxumZyKIP3mfAqS7BShks5bNcFRL/RHAFIl8N8k6/w/D/bEh/r9PYDdjHUSbcKPxeTfUlNSw4FHU3WVxBWOre+xmtphJtMVHAl4yt/cs9jlX/Xgh8eWzPU6YugJIjYjHj+qKKLgySw2RDSLxyZ7Lz3Esfq0pxhXAOZgdXfk2sL2huo4SfLdbM3Yhq3BdoImRZZSoHnLieuqnymaig8+UAJUlwODrtSJnfmbL6J9mSYkscI/tucy4Hca376ETstYfi3W5ml+G1W71K8tNDV80LMakAYSEf/6sOlb2G7/bmYYOdPyLLZ0DjFJTaQehupsX/M/rVTNV1CFmNM9vcz5se0ARtDhwdZ5oKAWUzcV3tpCaOOuJF8+jfWauhQ9vJLnjxVojaWZySN/FMWOruKZ0gcQ9/PjAu1asFKkQcgk72/v4htWFeB40SC+5KN7MPyrVt1UQrsWw82/rxcWjOcEMeinVZcu7SaRn83u8Sq+XWwKZAizf37Azvsq8aXWhvmQ0M/i4eb+UBI3/Tq83i+PsDur540uUb7nzaAm3JwSzqRa992lf4qfXsFYr01pUZmkwtWS6vXL7asI5e8DKauu9lSD1KzR04Mft49TQIrpWzEkmVzoT3OOKnJFOw=
